google.maps.__gjsload__('geometry', function(_){'use strict';var vy=function(a,b){return Math.abs(_.Ia(b-a,-180,180))};
var wy=function(a,b,c,d,e){if(!d){c=vy(a.lng(),c)/vy(a.lng(),b.lng());if(!e)return e=Math.sin(_.A(a.lat())),e=Math.log((1+e)/(1-e))/2,b=Math.sin(_.A(b.lat())),_.Ka(2*Math.atan(Math.exp(e+c*(Math.log((1+b)/(1-b))/2-e)))-Math.PI/2);a=e.fromLatLngToPoint(a);b=e.fromLatLngToPoint(b);return e.fromPointToLatLng(new _.N(a.x+c*(b.x-a.x),a.y+c*(b.y-a.y))).lat()}e=_.A(a.lat());a=_.A(a.lng());d=_.A(b.lat());b=_.A(b.lng());c=_.A(c);return _.Ia(_.Ka(Math.atan2(Math.sin(e)*Math.cos(d)*Math.sin(c-b)-Math.sin(d)*
Math.cos(e)*Math.sin(c-a),Math.cos(e)*Math.cos(d)*Math.sin(a-b))),-90,90)};var xy=function(){};
var yy={containsLocation:function(a,b){for(var c=_.Ia(a.lng(),-180,180),d=!!b.get("geodesic"),e=b.get("latLngs"),f=b.get("map"),f=!d&&f?f.getProjection():null,g=!1,h=0,k=e.getLength();h<k;++h)for(var n=e.getAt(h),p=0,q=n.getLength();p<q;++p){var r=n.getAt(p),v=n.getAt((p+1)%q),x=_.Ia(r.lng(),-180,180),w=_.Ia(v.lng(),-180,180),z=Math.max(x,w),x=Math.min(x,w);(180<z-x?c>=z||c<x:c<z&&c>=x)&&wy(r,v,c,d,f)<a.lat()&&(g=!g)}return g||yy.isLocationOnEdge(a,b)},isLocationOnEdge:function(a,b,c){c=c||1E-9;var d=
_.Ia(a.lng(),-180,180),e=b instanceof _.Md,f=!!b.get("geodesic"),g=b.get("latLngs");b=b.get("map");b=!f&&b?b.getProjection():null;for(var h=0,k=g.getLength();h<k;++h)for(var n=g.getAt(h),p=n.getLength(),q=e?p:p-1,r=0;r<q;++r){var v=n.getAt(r),x=n.getAt((r+1)%p),w=_.Ia(v.lng(),-180,180),z=_.Ia(x.lng(),-180,180),F=Math.max(w,z),D=Math.min(w,z);if(w=1E-9>=Math.abs(_.Ia(w-z,-180,180))&&(Math.abs(_.Ia(w-d,-180,180))<=c||Math.abs(_.Ia(z-d,-180,180))<=c))var w=a.lat(),z=Math.min(v.lat(),x.lat())-c,E=Math.max(v.lat(),
x.lat())+c,w=w>=z&&w<=E;if(w)return!0;if(180<F-D?d+c>=F||d-c<=D:d+c>=D&&d-c<=F)if(v=wy(v,x,d,f,b),Math.abs(v-a.lat())<c)return!0}return!1}};var zy={computeHeading:function(a,b){var c=_.Qb(a),d=_.Rb(a),e=_.Qb(b),d=_.Rb(b)-d;return _.Ia(_.Ka(Math.atan2(Math.sin(d)*Math.cos(e),Math.cos(c)*Math.sin(e)-Math.sin(c)*Math.cos(e)*Math.cos(d))),-180,180)},computeOffset:function(a,b,c,d){b/=d||6378137;c=_.A(c);var e=_.Qb(a);a=_.Rb(a);d=Math.cos(b);b=Math.sin(b);var f=Math.sin(e),e=Math.cos(e),g=d*f+b*e*Math.cos(c);return new _.L(_.Ka(Math.asin(g)),_.Ka(a+Math.atan2(b*e*Math.sin(c),d-f*g)))},computeOffsetOrigin:function(a,b,c,d){c=_.A(c);b/=d||6378137;
d=Math.cos(b);var e=Math.sin(b)*Math.cos(c);b=Math.sin(b)*Math.sin(c);c=Math.sin(_.Qb(a));var f=e*e*d*d+d*d*d*d-d*d*c*c;if(0>f)return null;var g=e*c+Math.sqrt(f),g=g/(d*d+e*e),h=(c-e*g)/d,g=Math.atan2(h,g);if(g<-Math.PI/2||g>Math.PI/2)g=e*c-Math.sqrt(f),g=Math.atan2(h,g/(d*d+e*e));if(g<-Math.PI/2||g>Math.PI/2)return null;a=_.Rb(a)-Math.atan2(b,d*Math.cos(g)-e*Math.sin(g));return new _.L(_.Ka(g),_.Ka(a))},interpolate:function(a,b,c){var d=_.Qb(a),e=_.Rb(a),f=_.Qb(b),g=_.Rb(b),h=Math.cos(d),k=Math.cos(f);
b=zy.zg(a,b);var n=Math.sin(b);if(1E-6>n)return new _.L(a.lat(),a.lng());a=Math.sin((1-c)*b)/n;c=Math.sin(c*b)/n;b=a*h*Math.cos(e)+c*k*Math.cos(g);e=a*h*Math.sin(e)+c*k*Math.sin(g);return new _.L(_.Ka(Math.atan2(a*Math.sin(d)+c*Math.sin(f),Math.sqrt(b*b+e*e))),_.Ka(Math.atan2(e,b)))},zg:function(a,b){var c=_.Qb(a),d=_.Rb(a),e=_.Qb(b),f=_.Rb(b);return 2*Math.asin(Math.sqrt(Math.pow(Math.sin((c-e)/2),2)+Math.cos(c)*Math.cos(e)*Math.pow(Math.sin((d-f)/2),2)))},computeDistanceBetween:function(a,b,c){c=
c||6378137;return zy.zg(a,b)*c},computeLength:function(a,b){var c=b||6378137,d=0;a instanceof _.Ib&&(a=a.getArray());for(var e=0,f=a.length-1;e<f;++e)d+=zy.computeDistanceBetween(a[e],a[e+1],c);return d},computeArea:function(a,b){return Math.abs(zy.computeSignedArea(a,b))},computeSignedArea:function(a,b){var c=b||6378137;a instanceof _.Ib&&(a=a.getArray());for(var d=a[0],e=0,f=1,g=a.length-1;f<g;++f)e+=zy.pn(d,a[f],a[f+1]);return e*c*c},pn:function(a,b,c){return zy.qn(a,b,c)*zy.yo(a,b,c)},qn:function(a,
b,c){var d=[a,b,c,a];a=[];for(c=b=0;3>c;++c)a[c]=zy.zg(d[c],d[c+1]),b+=a[c];b/=2;d=Math.tan(b/2);for(c=0;3>c;++c)d*=Math.tan((b-a[c])/2);return 4*Math.atan(Math.sqrt(Math.abs(d)))},yo:function(a,b,c){a=[a,b,c];b=[];for(c=0;3>c;++c){var d=a[c],e=_.Qb(d),d=_.Rb(d),f=b[c]=[];f[0]=Math.cos(e)*Math.cos(d);f[1]=Math.cos(e)*Math.sin(d);f[2]=Math.sin(e)}return 0<b[0][0]*b[1][1]*b[2][2]+b[1][0]*b[2][1]*b[0][2]+b[2][0]*b[0][1]*b[1][2]-b[0][0]*b[2][1]*b[1][2]-b[1][0]*b[0][1]*b[2][2]-b[2][0]*b[1][1]*b[0][2]?
1:-1}};var Ay={decodePath:function(a){for(var b=_.u(a),c=Array(Math.floor(a.length/2)),d=0,e=0,f=0,g=0;d<b;++g){var h=1,k=0,n;do n=a.charCodeAt(d++)-63-1,h+=n<<k,k+=5;while(31<=n);e+=h&1?~(h>>1):h>>1;h=1;k=0;do n=a.charCodeAt(d++)-63-1,h+=n<<k,k+=5;while(31<=n);f+=h&1?~(h>>1):h>>1;c[g]=new _.L(1E-5*e,1E-5*f,!0)}c.length=g;return c},encodePath:function(a){a instanceof _.Ib&&(a=a.getArray());return Ay.Up(a,function(a){return[Math.round(1E5*a.lat()),Math.round(1E5*a.lng())]})},Up:function(a,b){for(var c=[],
d=[0,0],e,f=0,g=_.u(a);f<g;++f)e=b?b(a[f]):a[f],Ay.Qj(e[0]-d[0],c),Ay.Qj(e[1]-d[1],c),d=e;return c.join("")},Qj:function(a,b){return Ay.Vp(0>a?~(a<<1):a<<1,b)},Vp:function(a,b){for(;32<=a;)b.push(String.fromCharCode((32|a&31)+63)),a>>=5;b.push(String.fromCharCode(a+63));return b}};_.Xc.google.maps.geometry={encoding:Ay,spherical:zy,poly:yy};_.m=xy.prototype;_.m.decodePath=Ay.decodePath;_.m.encodePath=Ay.encodePath;_.m.computeDistanceBetween=zy.computeDistanceBetween;_.m.interpolate=zy.interpolate;_.m.computeHeading=zy.computeHeading;_.m.computeOffset=zy.computeOffset;_.m.computeOffsetOrigin=zy.computeOffsetOrigin;_.oc("geometry",new xy);});
