google.maps.__gjsload__('poly', function(_){'use strict';var s1=function(a){for(a=a.toString(16);2>a.length;)a="0"+a;return a};var aba=function(a){var b=new _.eN(["mousemove","mouseup","mousewheel"]);_.QC(b,["offset","panes","projectionTopLeft","size"],a);return b};
var t1=function(a,b,c){var d=a.path;a=a.j;for(var e=[],f=a?[]:null,g=d[0]==d[d.length-2]&&d[1]==d[d.length-1],h=0,k=d.length-2;h<k;h+=2){var n=d[h],p=d[h+1],q=d[h+2],r=d[h+3],v,x;a&&(v=a[h/2],x=a[h/2+1]);var w,z;switch(b){case 0:w=n>=c;z=q>=c;break;case 1:w=n<=c;z=q<=c;break;case 2:w=p>=c;z=r>=c;break;case 3:w=p<=c,z=r<=c}!h&&w&&(e.push(n,p),a&&f.push(v));if(w!=z){var F;switch(b){case 0:case 1:F=(c-n)/(q-n);e.push(c,p+F*(r-p));break;case 2:case 3:F=(c-p)/(r-p),e.push(n+F*(q-n),c)}a&&f.push(v+F*(x-
v))}z&&(e.push(q,r),a&&f.push(x))}g&&e.length&&(e[0]!=e[e.length-2]||e[1]!=e[e.length-1])&&(e.push(e[0],e[1]),a&&f.push(a[a.length-1]));return{path:e,j:f}};var u1=function(a){var b=aba(a);_.I.addListener(b,"mousemove",_.ab);_.I.addListener(b,"mouseup",_.ab);_.I.addListener(b,"mousewheel",function(b){var d=a.get("mouseEventTarget");d&&_.I.trigger.apply(null,[d,"mousewheel"].concat(_.ej(arguments)))});return b};
var bba=function(a,b,c,d){for(var e=null,f=c*c,g=0,h=d.length;g<h;++g){var k=_.OI(a,b,c,d[g]);k&&k[2]<=f&&(f=k[2],e=k)}return e};var cba=function(a,b,c){for(var d=0,e=0,f=c.length;e<f;++e)d+=_.NI(a,b,c[e]);return!!(d&1)};var v1=function(a,b){for(var c=new _.L(0,0),d=new _.N(0,0),e=0,f=a.length;e<f;e+=2)_.L.call(c,a[e],a[e+1],!0),d=b.fromLatLngToPoint(c,d),a[e]=d.x,a[e+1]=d.y};
var w1=function(){var a=new _.Vf({clickable:!1,fillOpacity:0});a.bindTo("map",this);a.bindTo("strokeColor",this);a.bindTo("strokeOpacity",this);a.bindTo("strokeWeight",this);var b=["center","freeVertexPosition","freeVertexIsCenter"],c=new _.rv(b,"return",dba);_.QC(c,b,this);a.bindTo("center",c,"return");b=["center","radius","planetRadius","freeVertexPosition","freeVertexIsCenter"];c=new _.rv(b,"return",(0,_.t)(this.O,this));_.QC(c,b,this);a.bindTo("radius",c,"return");this.j=_.hN();this.j.bindTo("zIndex",
this);a.bindTo("zIndex",this.j,"ghostZIndex")};var dba=function(a,b,c){return c&&b||a};
var x1=function(a,b,c,d,e,f,g,h){var k=this,n=_.X("div",a);a=9+2*(1+c);_.nf(n,new _.O(a,a));_.sk.O(n);g.O(n,c,9,1,h?.5:1);var p=new _.II(f);p.bindTo("position",k);f=new _.MD(n);f.bindTo("position",p,"rawPosition");f.bindTo("containerPixelBounds",k,"mapPixelBounds");f.bindTo("panningEnabled",k);f.set("draggableCursor",d);this.j=n;this.U=b;this.V=c;this.oa=p;this.na=e;this.P=f;this.S=!1;this.O={};this.T=g;var q;this.Ba=[_.I.addListener(f,"dragstart",function(){p.set("referencePosition",k.get("position"));
p.set("snappingCallback",k.na);k.O.mouseout=!0;k.O.mouseover=!0;q=[_.I.forward(b,"mousemove",n),_.I.forward(b,"mouseup",n)];b.set("draggableCursor",d);b.set("active",!0)}),_.I.addListener(f,"dragend",function(){p.set("referencePosition",null);p.set("snappingCallback",null);p.set("rawPosition",p.get("position"));b.set("active",!1);q&&(_.G(q,_.I.removeListener),q=null)}),_.I.forward(f,"panbynow",k),_.I.forward(f,"dragstart",k),_.I.forward(f,"dragend",k),_.I.addListener(f,"mouseover",function(){k.S=
!0;y1(k)}),_.I.addListener(f,"mouseout",function(){k.S=!1;y1(k)})];_.G(z1,function(a){k.Ba.push(eba(k,a))})};var eba=function(a,b){function c(a){d.O[b]?d.O[b]=!1:(_.Za(a),_.I.trigger(d,b,a))}var d=a;return"rightclick"==b?_.I.addDomListener(d.j,"contextmenu",c):_.I.addListener(d.P,b,c)};var y1=function(a){var b;if(a.S){var c=_.EN(a.get("color"));c&&(c.P=Math.floor((c.P+255)/2),c.O=Math.floor((c.O+255)/2),c.j=Math.floor((c.j+255)/2),b=["#",s1(c.P),s1(c.O),s1(c.j)].join(""))}a.T.j(a.j,b||"white")};
var A1=function(a,b,c,d,e,f){function g(){h.S||_.I.trigger(h,"toolbar",{Lb:!1})}this.ta=a;this.V=b;this.U=c;this.O=_.X("div",e,_.tg);this.S=d;this.qa=f;this.j=[];a.forEach((0,_.t)(this.T,this));var h=this;this.na=[_.I.addListener(a,"insert_at",function(b){h.T(a.getAt(b),b);B1(h,b+1);g()}),_.I.addListener(a,"remove_at",function(a){var b=h.j[a];h.j.splice(a,1);h.oa(b);B1(h,a);g()}),_.I.addListener(a,"set_at",function(b){h.j[b].Od.set("latLngPosition",a.getAt(b));g()})]};
var B1=function(a,b){for(var c=a.j.length;b<c;++b)a.j[b].index=b};var C1=function(a,b){this.P=a;this.S=b;this.O=null;this.Ae=!1;this.j=new _.Ib;_.I.bind(this.j,"set_at",this,this.lr)};
var fba=function(a){var b=a.get("panes");if(!b)return null;b=new A1(a.j,gba,hba,!1,b.overlayMouseTarget,a.S);b.bindTo("projection",a);b.bindTo("zoom",a);b.bindTo("projectionCenterQ",a);b.bindTo("panningEnabled",a);b.bindTo("mapPixelBounds",a);b.bindTo("color",a);b.bindTo("zIndex",a);b.bindTo("offset",a);var c=a.P;c.bindTo("freeVertexPosition",b);var d,e;_.I.addListener(b,"dragstart",function(b){d=a.get("center");e=a.get("radius");c.set("freeVertexIsCenter",0==b);c.set("map",a.get("map"))});_.I.addListener(b,
"dragend",function(b,g){c.set("map",null);_.I.trigger(a,"toolbar",{Lb:!0,position:g,action:function(){a.set("center",d);a.set("radius",e)}})});_.I.forward(b,"dragstart",a);_.I.forward(b,"dragend",a);_.I.forward(b,"panbynow",a);return b};var D1=function(a){var b=a.O;b&&(b.unbindAll(),b.release(),_.I.clearInstanceListeners(b),a.O=null)};var E1=function(){};var F1=function(){};
var iba=function(a,b,c){function d(){a.get("editable")?jba(a,b,c):(G1(a),_.I.trigger(a,"toolbar",{Lb:!1}))}a.editable_changed=d;d()};
var jba=function(a,b,c){if(!a.P){var d=new _.jN(a,!0);a.S=d;var e=new w1;e.bindTo("strokeColor",d);e.bindTo("strokeOpacity",d,"ghostStrokeOpacity");e.bindTo("strokeWeight",d);e.bindTo("center",a);e.bindTo("radius",a);e.bindTo("planetRadius",c);e.bindTo("zIndex",a);a.T=e;var f=b.__gm;a.j=u1(f);var g=_.LI(f,a),h=_.Vj()?9:0,k=_.sk.T?new E1:new F1,e=new C1(e,function(b,c,d,e){return new x1(b,a.j||null,h,c,g,d,k,e)});e.set("map",b);e.bindTo("center",a);e.bindTo("radius",a);e.bindTo("planetRadius",c);e.bindTo("panes",
f);e.bindTo("projection",b);e.bindTo("zoom",f);e.bindTo("projectionCenterQ",f);e.bindTo("panningEnabled",b,"draggable");e.bindTo("mapPixelBounds",f,"pixelBounds");e.bindTo("offset",f);e.bindTo("color",d,"strokeColor");e.bindTo("zIndex",a);a.P=e;_.I.addListener(e,"dragstart",function(){a.set("capturing",!0)});_.I.addListener(e,"dragend",function(){a.set("capturing",!1)});_.I.forward(e,"panbynow",f);_.I.forward(e,"toolbar",a)}};
var G1=function(a){var b=a.P;b&&(b.unbindAll(),b.set("map",null),_.I.clearInstanceListeners(b),delete a.P,a.j.release(),delete a.j,a.set("capturing",!1),a.T.unbindAll(),delete a.T,a.S.release(),delete a.S)};var H1=function(a,b,c,d,e,f){this.O=a;this.Ua=c;a=a.get("center");b=c.fromDivPixelToLatLng(b);this.S=d(a,b);this.j=_.DA(b,a);this.P=f};
var I1=function(){var a=this;_.S.call(a);var b=this.j=new _.Md;b.P=!0;b.bindTo("capturing",a);b.bindTo("cursor",a);b.bindTo("map",a);b.bindTo("strokeColor",a);b.bindTo("strokeOpacity",a);b.bindTo("strokeWeight",a);b.bindTo("strokePosition",a);b.bindTo("fillColor",a);b.bindTo("fillOpacity",a);b.bindTo("clickable",a);b.bindTo("zIndex",a);b.bindTo("suppressUndo",a);var c=this.O=[];_.G(z1,function(d){c.push(_.I.forward(b,d,a))});c.push(_.I.forward(a,"toolbar",b))};
var kba=function(a,b){var c=Array(250),d=[c],e=_.A(a.lat()),f=_.A(a.lng()),g=Math.cos(b),h=Math.sin(b),k=Math.cos(e),n=Math.sin(e);if(1E-6<k)for(var p=0;250>p;++p){var q=p/250*Math.PI*4,q=q+Math.sin(q+Math.PI),r=q/2,v=n*g+k*h*Math.cos(r),q=Math.asin(v),r=f+Math.atan2(Math.sin(r)*h*k,g-n*v),r=_.Ia(r,-Math.PI,Math.PI);c[p]=new _.L(_.Ka(q),_.Ka(r))}else for(p=_.Ka(b),f=0<a.lat()?a.lat()-p:a.lat()+p,p=0;250>p;++p)c[p]=new _.L(f,360*p/250);e-b<-Math.PI/2&&(c=[new _.L(-90,-200,!0),new _.L(90,-200,!0),new _.L(90,
-100,!0),new _.L(90,0,!0),new _.L(90,100,!0),new _.L(90,200,!0),new _.L(-90,200,!0),new _.L(-90,100,!0),new _.L(-90,0,!0),new _.L(-90,-100,!0),new _.L(-90,-200,!0)],d.push(c));return d};var J1=function(a){this.y=this.x=0;this.j=a};var K1=function(a){var b=Math.sqrt(L1(a,a));1E-12>b||(a.x/=b,a.y/=b,a.j/=b)};var L1=function(a,b){return a.x*b.x+a.y*b.y+a.j*b.j};var M1=function(a,b,c){c.x=a.y*b.j-a.j*b.y;c.y=a.j*b.x-a.x*b.j;c.j=a.x*b.y-a.y*b.x};
var N1=function(a,b){var c=_.A(a[0]),d=_.A(a[1]),e=Math.cos(c);b.x=Math.cos(d)*e;b.y=Math.sin(d)*e;b.j=Math.sin(c)};var O1=function(a,b){var c=Math.atan2(a.y,a.x);b[0]=_.Ka(Math.atan2(a.j,Math.sqrt(a.x*a.x+a.y*a.y)));b[1]=_.Ka(c)};var lba=function(a,b,c){c.x=a.x+b.x;c.y=a.y+b.y;c.j=a.j+b.j;K1(c)};
var P1=function(a,b,c,d,e,f){this.j=a;this.Ua=c;this.U=e;this.T=f;var g=mba(this);b=c.fromDivPixelToLatLng(b);this.V=_.DA(g,b);this.na=d(g,b);var h=this.S=[];a.get("latLngs").forEach(function(a){var b=[];a.forEach(function(a){b.push({heading:d(g,a),ad:_.DA(a,g)})});h.push(b)});this.O=g;this.P=b.lng()-g.lng()};
var mba=function(a){a=a.j.get("latLngs");var b=new J1(0),c=new J1(0);a.forEach(function(a){a.forEach(function(a){N1([a.lat(),a.lng()],c);b.x+=c.x;b.y+=c.y;b.j+=c.j})});K1(b);a=[0,0];O1(b,a);a[0]=_.Ha(a[0],-89,89);return new _.L(a[0],a[1])};var Q1=function(a,b,c,d,e){_.Cj.call(this,a,b);_.B(c)&&(this.path=c);_.B(d)&&(this.vertex=d);_.B(e)&&(this.edge=e)};var R1=function(a,b,c){this.O=a;this.Ua=c;this.j=c.fromDivPixelToLatLng(b);var d=this.P=[];a.get("latLngs").forEach(function(a){d.push(_.ej(a.getArray()))})};
var S1=function(a,b){this.V=a;this.O=_.X("div",null,null,T1);this.O.style.backgroundColor="red";_.tk(this.O,.01);var c=this.P=new _.MD(this.O);c.bindTo("position",this);c.bindTo("containerPixelBounds",this);c.bindTo("panningEnabled",this);c.set("draggableCursor","pointer");c.set("draggingCursor","pointer");c.set("size",T1);c.set("anchorPoint",U1);this.U=[_.I.bind(c,"dragstart",this,this.ii),_.I.bind(c,"dragend",this,this.fg),_.I.bind(c,"click",this,this.Rl),_.I.bind(c,"mousedown",this,this.Vl),_.I.bind(c,
"mousemove",this,this.Wl),_.I.bind(c,"mouseup",this,this.Xl),_.I.forward(c,"panbynow",this)];_.Vj()&&(c=b.__gm,_.I.bind(c,"movestart",this,this.Tl),_.I.bind(c,"move",this,this.Ul),_.I.bind(c,"moveend",this,this.Sl));c=new _.rv(["mousedown","dragging"],"active",function(a,b){return a||b});c.bindTo("dragging",this,null,!0);c.bindTo("mousedown",this,null,!0);this.bindTo("active",c,null,!0)};var V1=function(a,b){var c;c=b?1E9:(a.j.get("zIndex")||0)-2;_.qk(a.O,c)};
var W1=function(a,b,c){var d=a.get("position"),d=a.Ua.fromDivPixelToLatLng(d);_.I.trigger(a.j,b,new _.Cj(d,c))};var X1=function(a,b){var c=a.__gm;b.bindTo("panningEnabled",a,"draggable");b.bindTo("panes",c);b.bindTo("projectionController",c);b.bindTo("containerPixelBounds",c,"pixelBounds");c.Xa=_.I.forward(b,"panbynow",c)};
var Y1=function(a,b){function c(){var b=a.getMap();a.getDraggable()&&(_.Y(b,"Od"),_.il("Od","-p",a,!(!b||!b.Ga)))}a.draggable_changed=c;c();a.oa=[_.I.addListener(a,"mouseover",function(c){null==c.vertex&&null==c.edge&&b.set("poly",a)}),_.I.addListener(a,"click",function(b){null==b.vertex&&null==b.edge&&a.getDraggable()&&(b=a.getMap(),_.il("Od","-i",a,!(!b||!b.Ga)))}),_.I.addListener(a,"mouseout",function(a){null!=a.vertex||null!=a.edge||_.ii(a.Fb)||b.set("poly",null)})]};
var nba=function(a){var b=a.__gm.P;b.j||(_.M("geometry",function(c){var d=new S1(function(a,b,d){return new H1(a,b,d,c.computeHeading,0,c.computeOffsetOrigin)},a);X1(a,d);b.j=function(b){Y1(b,d);var c=b.Pr=new _.rv(["mapType"],"planetRadius",_.Gd);c.bindTo("mapType",a.__gm);var g=b.Ii=new I1;g.set("map",a);g.bindTo("radius",b);g.bindTo("center",b);g.bindTo("capturing",b);g.bindTo("clickable",b);g.bindTo("cursor",b);g.bindTo("fillColor",b);g.bindTo("fillOpacity",b);g.bindTo("strokeColor",b);g.bindTo("strokeOpacity",
b);g.bindTo("strokeWeight",b);g.bindTo("strokePosition",b);g.bindTo("zIndex",b);g.bindTo("suppressUndo",b);g.bindTo("planetRadius",c);b.Na=[];_.G(z1,function(a){b.Na.push(_.I.forward(g,a,b))});b.Na.push(_.I.forward(b,"toolbar",g));iba(b,a,c);_.Y(a,"Oc");_.il("Oc","-p",b,!(!a||!a.Ga));_.I.addListener(b,"click",function(){_.il("Oc","-i",b,!(!a||!a.Ga))})}}),b.onRemove=function(a){var b=a.Ii;b.unbindAll();b.set("map",null);b.release();delete a.Ii;_.G(a.Na,_.I.removeListener);delete a.Na;delete a.editable_changed;
G1(a);_.jl("Oc","-p",a)})};var oba=function(a,b,c,d){a.capturing_changed=function(){if(a.get("capturing"))if(0==a.get("clickable")){var e=a.O=new _.mN;e.bindTo("draggableCursor",a,"cursor");e.set("active",!0);b.bindTo("cursor",e);d.kc(e)}else d.He(c,a);else a.O?(d.Yd(a.O),a.O.unbindAll(),b.unbind("cursor"),b.set("cursor",""),delete a.O):d.Ge(c,a)}};
var Z1=function(a,b,c){var d=this;this.V=a;this.S=b;this.T=c;this.O={};this.j={};this.P=0;this.U=function(a){$1(d,this,a)};a.j=function(a){var b=d.get("projection"),b=a.Ff={style:a2(d.T,a),fd:b2(a,b)};c2(d,a);a.changed=d.U;_.wc(d.S,b)};a.onRemove=function(a){var b=a.Ff;delete a.Ff;d.S.remove(b);delete a.changed;d2(a);a=_.mb(a);delete d.O[a];delete d.j[a]}};var $1=function(a,b,c){var d=_.mb(b);c in pba&&(a.j[d]=b,d2(b));c in qba&&(a.O[d]=b);e2(a)};
var e2=function(a){a.P||(a.P=_.Wa(function(){a.P=0;var b=a.O;a.O={};var c=a.j;a.j={};for(var d in b){var e=b[d],f=e.Ff;f.style=a2(a.T,e);f.eh&&!c[d]&&f.eh()}var b=a.S,g=a.get("projection");for(d in c)e=c[d],f=e.Ff,b.remove(f),f.fd=b2(e,g),_.wc(b,f),c2(a,e)}))};
var c2=function(a,b){function c(){$1(e,b,"latLngs")}var d=b.get("latLngs");if(d){for(var e=a,f=_.mb(b),g=d.getArray(),h=0,k=g.length;h<k;++h){var n=g[h];f2(n);n.O.wb[f]=n.S.wb[f]=n.P.wb[f]=c}f2(d);d.S.wb[f]=d.P.wb[f]=function(a,b){g2(b,f);c()};d.O.wb[f]=c}};var d2=function(a){var b=a.get("latLngs");if(b){a=_.mb(a);g2(b,a);for(var b=b.getArray(),c=0,d=b.length;c<d;++c)g2(b[c],a)}};
var f2=function(a){a.O||(a.O=function(b){_.Fa(a.O.wb,function(a,d){d(b)})},a.O.wb={});a.S||(a.S=function(b,c){_.Fa(a.S.wb,function(a,e){e(b,c)})},a.S.wb={});a.P||(a.P=function(b,c){_.Fa(a.P.wb,function(a,e){e(b,c)})},a.P.wb={})};var g2=function(a,b){a.O&&delete a.O.wb[b];a.S&&delete a.S.wb[b];a.P&&delete a.P.wb[b]};
var h2=function(){var a=this.O=_.X("div");_.qk(a,-202);_.pk(a,"pointer");_.sk.O(a);_.AC(a);this.j=_.aC(rba,a,i2,j2);_.I.bind(this,"toolbar",this,this.Yl);_.I.Fa(a,"click",this,this.Rp);_.I.addDomListener(a,"mouseover",(0,_.t)(this.Hf,this,sba));_.I.addDomListener(a,"mouseout",(0,_.t)(this.Hf,this,i2));_.I.Fa(a,"mousedown",this,function(a){_.cb(a);this.Hf(tba)});_.I.addDomListener(a,"mousemove",_.cb);_.I.addDomListener(a,"mouseup",_.cb)};var k2=function(a){a.P&&_.I.clearListeners(a.P,"suppressundo_changed")};
var uba=function(a,b,c,d){a.Hf(i2);_.hk(a.O,new _.N(b.x+l2.x,b.y+l2.y));a.S=c;k2(a);a.P=d;_.mk(a.O);_.I.addListener(d,"suppressundo_changed",function(){d.get("suppressUndo")&&a.td()})};
var m2=function(a){var b=this;this.j=a;_.I.addListener(a,"set_at",function(c){_.I.trigger(b,"set_at",c);var d=a.getLength();0==c&&1<d&&_.I.trigger(b,"set_at",d)});_.I.addListener(a,"insert_at",function(c){_.I.trigger(b,"insert_at",c);var d=a.getLength();2==d?_.I.trigger(b,"insert_at",2):0==c&&1<d&&_.I.trigger(b,"set_at",d)});_.I.addListener(a,"remove_at",function(c){_.I.trigger(b,"remove_at",c);var d=a.getLength();1==d?_.I.trigger(b,"remove_at",1):0==c&&1<d&&_.I.trigger(b,"set_at",d)})};
var n2=function(a,b,c){this.O=a;this.P=b;this.j=c;this.Ba=[_.I.bind(a,"set_at",this,this.$k),_.I.bind(a,"insert_at",this,this.Yh),_.I.bind(a,"remove_at",this,this.Zk)];b=0;for(a=a.getLength();b<a;++b)this.Yh(b)};var o2=function(a,b,c){var d=a.get("projection");if(d){var e=a.O,f=e.getAt(c),g=a.P,h=a.get("geodesic");0<c&&g.setAt(c-1,p2(e.getAt(c-1),f,h,d,a.j));c<e.getLength()-1&&(a=p2(f,e.getAt(c+1),h,d,a.j),b?g.insertAt(c,a):g.setAt(c,a))}};
var p2=function(a,b,c,d,e){c?d=e(a,b,.5):(180<Math.abs(a.lng()-b.lng())&&(a=new _.L(a.lat(),_.Ia(a.lng(),b.lng()-180,b.lng()+180),!0)),a=d.fromLatLngToPoint(a),b=d.fromLatLngToPoint(b),d=d.fromPointToLatLng(new _.N((a.x+b.x)/2,(a.y+b.y)/2)));return d};var q2=function(a,b,c,d){this.T=a;this.S=b;this.na=c;this.V=d;this.O=[];this.j=[];this.U=[]};
var r2=function(a,b,c){var d=s2(a,b,c,!1),e=a.T,f;_.I.addListener(d,"dragstart",function(c){f=b.getAt(c);var h=b.getArray(),k=a.S,n=h.length;if(2>n)e.set("anchors",[]);else{var p=h[k&&0==c?n-1:c-1];c=h[k&&c==n-1?0:c+1];h=[];p&&h.push(p);c&&h.push(c);e.set("anchors",h)}e.bindTo("freeVertexPosition",d);e.set("map",a.get("map"))});_.I.addListener(d,"dragend",function(c,d){e.set("map",null);_.I.trigger(a,"toolbar",{Lb:!0,position:d,action:function(){b.setAt(c,f)}})});return d};
var t2=function(a,b,c){var d=new _.Ib,e=a.S?new m2(b):b,f=new n2(e,d,a.V);f.bindTo("geodesic",a);f.bindTo("projection",a);var g=s2(a,d,c,!0);g.P=f;var h=a.T;_.I.addListener(g,"dragstart",function(b){b=[e.getAt(b),e.getAt(b+1)];h.set("anchors",b);h.bindTo("freeVertexPosition",g);h.set("map",a.get("map"))});_.I.addListener(g,"dragend",function(c,e){b.insertAt(c+1,d.getAt(c));h.set("map",null);_.I.trigger(a,"toolbar",{Lb:!0,position:e,action:function(){b.removeAt(c+1)}})});return g};
var s2=function(a,b,c,d){var e=new A1(b,["pointer"],[0],d,c,a.na);e.bindTo("projection",a);e.bindTo("zoom",a);e.bindTo("projectionCenterQ",a);e.bindTo("panningEnabled",a);e.bindTo("mapPixelBounds",a);e.bindTo("color",a);e.bindTo("zIndex",a);e.bindTo("offset",a);_.I.forward(e,"dragstart",a);_.I.forward(e,"dragend",a);_.I.forward(e,"panbynow",a);_.I.forward(e,"toolbar",a);_.G(z1,function(c){_.I.addListener(e,c,function(g){var h=b.getAt(g),k;if(a.S)for(var n=d?a.j:a.O,p=0;p<n.length;++p)if(n[p]==e){k=
p;break}_.I.trigger(a,c,new Q1(h,void 0,k,d?void 0:g,d?g:void 0))})});return e};var u2=function(a){var b=(0,_.t)(a.P,a);_.G(a.O,b);_.G(a.j,b);a.O.length=0;a.j.length=0;_.G(a.U,_.I.removeListener);a.U.length=0};
var v2=function(a,b,c){function d(){g[x++]=k.Qa[0];g[x++]=k.Qa[1];f&&(h[q++]=k.ad);n=k}var e=a.path,f=a.j;if(!e.length)return a;var g=Array(e.length),h=f?Array(f.length):null;a=[];var k,n=w2();g[0]=n.Qa[0]=e[0];g[1]=n.Qa[1]=e[1];f&&(h[0]=n.ad=f[0]);n.depth=0;N1(n.Qa,n.Pd);for(var p=1,q=1,r=[],v=2,x=2;v<e.length||r.length;)if(r.length?k=r.pop():(k=w2(),k.depth=0,k.Qa[0]=e[v++],k.Qa[1]=e[v++],f&&(k.ad=f[p++]),N1(k.Qa,k.Pd)),12<=Math.max(n.depth,k.depth))d();else{var w=new _.jf;w.ua=Math.min(n.Qa[0],
k.Qa[0]);w.wa=Math.max(n.Qa[0],k.Qa[0]);w.ra=Math.min(n.Qa[1],k.Qa[1]);w.ya=Math.max(n.Qa[1],k.Qa[1]);if(_.wj(b,w)){var z=w2();lba(n.Pd,k.Pd,z.Pd);O1(z.Pd,z.Qa);z.depth=Math.max(n.depth,k.depth)+1;f&&(z.ad=(n.ad+k.ad)/2);var F=w.ra-1E-6,D=w.ya+1E-6,w=z.Qa;w[1]=vba(F,D,w[1]);wba(n.Qa,k.Qa,a);Math.max(Math.abs(z.Qa[0]-a[0]),Math.abs(z.Qa[1]-a[1]))<=c?d():(r.push(k),r.push(z))}else d()}return{path:g,j:h}};var wba=function(a,b,c){c[0]=(a[0]+b[0])/2;c[1]=(a[1]+b[1])/2};
var vba=function(a,b,c){for(;c<a;)c+=360;for(;c>b;)c-=360;return c};var w2=function(){return{Qa:[0,0],Pd:new J1(0)}};var xba=function(a){return function(b,c){var d;d="px"==b.tc?b.value/a:(d=_.u(c))?b.value/100*c[d-1]:0;return d}};var yba=function(a,b,c,d){--b;if(!(0>b)){var e=a.length,f=0;for(d(0);f<b;){var g=1<<e,h=e?a[e-1][f/g]:0,k=f+g;k>=b&&(k=b);e&&c(f,k,h)?--e:(d(k),f=k,f&g||++e)}}};
var zba=function(a,b){return function(c,d){if(0==c)return!0;for(var e=a[c],f=a[d],g=0,h;h=b[g];++g){var k=h.offset;if(h=h.repeat){if(Math.floor((e-k)/h)!=Math.floor((f-k)/h))return!0}else if(e<k&&k<=f)return!0}return!1}};
var Aba=function(a,b,c,d){var e=a.ua,f=a.ra,g=a.wa,h=a.ya;return function(a,n,p){var q=d[2*a],r=d[2*a+1];a=d[2*n];n=d[2*n+1];var v=Math.min(r,n)-p,x=Math.max(q,a)+p,w=Math.max(r,n)+p;Math.min(q,a)-p<=g&&e<=x&&v<=h&&f<=w?p>b?p=!0:(v=c.fromLatLngToPoint(new _.L(q,r,!0)),x=c.fromLatLngToPoint(new _.L(a,n,!0)),v=c.fromPointToLatLng(new _.N((v.x+x.x)/2,(v.y+x.y)/2),!0),r=(r+n)/2,q=(q+a)/2-v.lat(),a=r-v.lng(),p=Math.sqrt(q*q+a*a)+p>b):p=!1;return p}};
var Bba=function(a,b,c){return function(d,e,f){var g=d.path,h=d.j,k=Aba(a,b,c,g);d=k;if(h){var n=zba(h,f);d=function(a,b,c){return k(a,b,c)||n(a,b)}}var p=[],q=h?[]:null;yba(e,g.length/2,d,function(a){p.push(g[2*a],g[2*a+1]);h&&q.push(h[a])});return{path:p,j:q}}};var x2=function(a,b){var c=0;_.Ja(a,-16,.001)&&(c|=1);_.Ja(a,272,.001)&&(c|=2);_.Ja(b,-16,.001)&&(c|=4);_.Ja(b,272,.001)&&(c|=8);return c};
var y2=function(a,b,c){var d=a.fromPointToLatLng(c);a=a.fromPointToLatLng(new _.N(c.x+b,c.y+b));return Math.min(Math.abs(d.lat()-a.lat()),Math.abs(d.lng()-a.lng()))};
var z2=function(a,b,c){b=this.U=1<<b;this.T=c;var d=_.kf((256*a.x-16)/b,(256*a.y-16)/b,(256*(a.x+1)+16)/b,(256*(a.y+1)+16)/b);a=new _.N(d.ua,d.ra);var d=new _.N(d.wa,d.ya),e=c.fromPointToLatLng(a,!0),f=c.fromPointToLatLng(d,!0),g=Math.min(e.lat(),f.lat()),h=Math.max(e.lat(),f.lat()),k=Math.min(e.lng(),f.lng()),e=Math.max(e.lng(),f.lng()),f=(k+e)/2,n=_.Ia(f,-180,180),k=k+(n-f),e=e+(n-f),f=_.kf(g,k,h,e),g=new _.L(g,k,!0);c.fromLatLngToPoint(g,a);h=new _.L(h,e,!0);c.fromLatLngToPoint(h,d);d=new _.jf([a,
d]);this.O=f;this.j=d;a=.5/b;d=this.j;this.S=Math.min(y2(c,a,new _.N(d.ua,d.ra)),y2(c,a,new _.N(d.wa,d.ya)));this.V=Bba(this.O,this.S,c);this.P=xba(b)};var A2=function(a,b,c){this.P=a;this.O=b;this.S=c};var Cba=function(a){return _.La(a,function(a){return _.La(a,function(a){return Math.round(a)})})};
var Dba=function(a,b,c,d){function e(){a.get("editable")?(Eba(a,b,d),_.Y(b,"Oe"),_.il("Oe","-p",a,!(!b||!b.Ga))):(_.I.trigger(c,"toolbar",{Lb:!1,Dc:a}),B2(a))}a.editable_changed=e;e();a.U=_.I.addListener(a,"toolbar",function(b){b.Dc=a;_.I.trigger(c,"toolbar",b)})};
var Eba=function(a,b,c){if(!a.T){var d=new _.jN(a,a.vb);a.V=d;var e=new _.iN;e.bindTo("strokeColor",d);e.bindTo("strokeOpacity",d,"ghostStrokeOpacity");e.bindTo("strokeWeight",d);e.bindTo("geodesic",a);e.bindTo("zIndex",a);a.yc=e;var f=b.__gm;a.j=u1(f);var g=_.LI(f,a),h=_.Vj()?9:0,k=_.sk.T?new E1:new F1,n=new q2(e,a.vb,function(b,c,d,e){return new x1(b,a.j||null,h,c,g,d,k,e)},c);n.set("map",b);n.bindTo("paths",a,"latLngs");n.bindTo("panes",f);n.bindTo("projection",b);n.bindTo("zoom",f);n.bindTo("projectionCenterQ",
f);n.bindTo("panningEnabled",b,"draggable");n.bindTo("mapPixelBounds",f,"pixelBounds");n.bindTo("offset",f);n.bindTo("color",d,"strokeColor");n.bindTo("zIndex",a);n.bindTo("geodesic",a);n.bindTo("suppressGhostControlPoints",a);a.T=n;a.na=[_.I.addListener(a,"mousedown",function(){a.set("capturing",!0)}),_.I.addListener(a,"mouseup",function(){a.set("capturing",!1)})];_.I.addListener(a,"click",function(){a.get("editable")&&_.il("Oe","-i",a,!(!b||!b.Ga))});_.I.forward(n,"panbynow",f);_.I.forward(n,"toolbar",
a);_.G(z1,function(b){_.I.forward(n,b,a)})}};var B2=function(a){var b=a.T;b&&(b.unbindAll(),b.set("map",null),_.I.clearInstanceListeners(b),delete a.T,a.j.unbindAll(),a.j.release(),delete a.j,a.set("capturing",!1),_.G(a.na,_.I.removeListener),delete a.na,a.yc.unbindAll(),delete a.yc,a.V.release(),delete a.V)};var C2=function(a,b){this.j=a;this.O=_.Ij(b,Math.min(2,_.pf()));this.tileSize=new _.O(256,256)};
var D2=function(a,b,c,d){this.V=c;this.T=a;a=_.gk(a);this.j=E2(a,b,d);_.hk(this.j,_.tg);this.U=F2(this.j,d);this.oa=E2(a,b,d);this.qa=F2(this.oa,d);this.Aa=new _.QI(this.U);this.Ea=new _.QI(this.qa);this.O={};this.P=0};var E2=function(a,b,c){a=a.createElement("canvas");a.width=b.width*c;a.height=b.height*c;a.style.width=_.V(b.width);a.style.height=_.V(b.height);_.rk(a);return a};var F2=function(a,b){var c=a.context=a.getContext("2d");c.scale(b,b);c.lineCap=c.lineJoin="round";return c};
var G2=function(a){a.P||(a.P=_.Wa(function(){a.P=0;var b=Fba(a);if(b.length){a.j.parentNode||a.T.appendChild(a.j);var c=a.U,d=a.qa;c.clearRect(0,0,256,256);for(var e=0,f;f=b[e];++e){var g=f.O,h=g.U;_.Ja(1,h)?(a.V(c,f.ab,g.strokeColor,g.j,g.P,g.T,g.fillColor,g.O),H2(f.j,g.S,c,a.Aa,1)):(d.clearRect(0,0,256,256),a.V(d,f.ab,g.strokeColor,g.j/h,g.P,g.T),H2(f.j,g.S,d,a.Ea,h),c.globalAlpha=h,c.drawImage(a.oa,0,0,256,256))}}else a.j.parentNode&&a.T.removeChild(a.j)}))};
var H2=function(a,b,c,d,e){for(var f=0,g=a.length;f<g;++f){var h=b[f],k=c,n=d,p=a[f],q=h.S,r=h.scale,v=h.rotation,x=h.T,w=h.strokeColor,z=h.j/e,F=h.P,D=h.fillColor,h=h.O/e;k.beginPath();for(var E=0,H=p.length;E<H;E+=3)n.Zb(q,p[E],p[E+1],v+(x?p[E+2]:0),r);h&&(k.fillStyle=D,k.globalAlpha=h,k.fill());F&&(k.lineWidth=F,k.strokeStyle=w,k.globalAlpha=z,k.stroke())}};var Fba=function(a){var b=[];a=a.O;for(var c in a)b.push(a[c]);b.sort(function(a,b){return a.zIndex-b.zIndex});return b};
var Gba=function(a,b){function c(a,b){a.beginPath();for(var c=0,d;d=b[c];++c)if(d.length){a.moveTo(Math.round(d[0]),Math.round(d[1]));for(var e=2,f=d.length;e<f;)a.lineTo(Math.round(d[e++]),Math.round(d[e++]))}}var d=a.createElement("canvas");d.width=d.height=256*b;var e=d.getContext("2d");e.lineCap=e.lineJoin="round";e.scale(b,b);var f=[function(a,b,c,d,e){a.lineWidth=e;a.strokeStyle=c;a.globalAlpha=d;a.stroke()},function(a,b,c,d,e){a.lineWidth=2*e;a.strokeStyle=c;a.globalAlpha=d;a.save();a.clip();
a.stroke();a.restore()},function(a,b,f,n,p){e.lineWidth=2*p;e.strokeStyle=f;e.globalCompositeOperation="source-over";e.clearRect(0,0,256,256);c(e,b);e.stroke();e.globalCompositeOperation="destination-out";e.fill();a.globalAlpha=n;a.drawImage(d,0,0,256,256)}];return function(a,b,d,e,p,q,r,v){c(a,b);v&&(a.fillStyle=r,a.globalAlpha=v,a.fill());if(p)f[q](a,b,d,e,p)}};
var I2=function(a,b,c,d,e){this.j=a;this.O=d;this.P=e;a.setAttribute("dir","ltr");a.style.overflow="hidden";c&&_.nf(a,new _.O(b.width-1,b.height-1))};var Hba=function(a,b){for(var c=[],d=new _.N(0,0),e=0,f=b.length;e<f;e+=3){var g=J2(a,1E3);d.x=b[e];d.y=b[e+1];_.hk(g,d);c.push(g)}return c};var J2=function(a,b){var c=_.AD("gm_v:shape",a.j);a.O(c);_.nf(c,new _.O(1,1));var d=b||1;c.coordsize=d+" "+d;c.coordorigin="0 0";return c};var K2=function(a,b,c,d){this.U=a;this.P=b;this.S=c;this.O=d;this.j=null};
var Iba=function(a,b,c,d,e){var f=this;this.O=b;this.j=d;this.P=e;a.j=function(a){L2(f,a)};a.onRemove=function(a){delete a.eh;f.O.remove(a.Ta);a=a.fd;var b=a.Wa,c;for(c in b){var d=b[c],e=d.Va;e.j.ta(d);delete e.Wa[_.mb(d)]}a.Wa={};c=a.Vb;_.jl(c.vb?"Op":"Ol","-v",c)};c.j=function(a){M2(f,a)};c.onRemove=function(a){f.j.remove(a.Ta);var b=a.Wa,c;for(c in b){var d=b[c],e=d.S;delete e.Wa[_.mb(d)];d=e.Vb;_.jl(d.vb?"Op":"Ol","-v",d)}a.Wa={}};a=a.O;for(var g in a)L2(f,a[g]);c=c.O;for(g in c)M2(f,c[g])};
var L2=function(a,b){b.eh=function(){var a=b.fd.Wa,c;for(c in a){var d=a[c];d.O=b.style;d.zIndex=b.style.zIndex;d.Va.j.S(d)}};var c=b.fd,d=c.Ta;d.Dc=b;b.Ta=d;_.WI(a.O,d);for(var d=a.j.search(d),e=0,f=d.length;e<f;++e)N2(b,d[e].$b||null);0<d.length&&(c=c.Vb,_.il(c.vb?"Op":"Ol","-v",c,a.P))};var M2=function(a,b){var c=b.Ta;c.$b=b;_.WI(a.j,c);for(var c=a.O.search(b.Ta),d=0,e=c.length;d<e;++d)N2(c[d].Dc||null,b),_.il(c[d].Dc.fd.Vb.vb?"Op":"Ol","-v",c[d].Dc.fd.Vb,a.P)};
var N2=function(a,b){for(var c=a.fd,d=b.O,e=c.P,f=c.O,g=c.j,h=[],k=[],n=0,p=g.length;n<p;++n)k.push([]);n=0;for(p=e.length;n<p;++n){var q=e[n],r=q.O,v;v=d;var x=g,w=r.j,z=[];if(w)for(var F=0,D=void 0;D=x[F];++F)z.push({offset:v.P(D.offset,w),repeat:v.P(D.repeat,w)});v=z;r=q.j?d.V(r,q.j,v):{path:_.ej(r.path),j:r.j};if(r.path.length&&(f&&(r=v2(r,d.O,d.S)),v1(r.path,d.T),q=d.j,r=t1(r,0,q.ua),r=t1(r,1,q.wa),r=t1(r,2,q.ra),r=t1(r,3,q.ya),x=r.path,x.length)){h.push(x);w=d.U;z=d.j.ua;F=d.j.ra;q=0;for(D=
x.length;q<D;q+=2)x[q]=(x[q]-z)*w-16,x[q+1]=(x[q+1]-F)*w-16;for(q=0;w=v[q];++q){x=w.offset;w=w.repeat;if(z=r.j){for(var F=r.path,D=[],E=0,H=F.length-2;E<H;){var P=F[E],U=F[E+1],Z=z[E/2],oa=Z-x,E=E+2,Ya=F[E],$a=F[E+1];if(!(x2(P,U)&x2(Ya,$a))){for(;_.Ja(P,Ya)&&_.Ja(U,$a)&&E<H;)E+=2,Ya=F[E],$a=F[E+1];var Bb=z[E/2]-x,sc=Math.atan2(Ya-P,U-$a);0==Z&&(oa-=1E-9);if(w)for(Z=Math.floor(Bb/w)*w;Z>oa;){var cf=(Z-oa)/(Bb-oa);D.push(P+(Ya-P)*cf,U+($a-U)*cf,sc);Z-=w}else 0>oa&&0<=Bb&&(oa=(0-oa)/(Bb-oa),D.push(P+
(Ya-P)*oa,U+($a-U)*oa,sc))}}x=D}else x=null;x&&(k[q]=k[q].concat(x))}}}h.length&&(d={},d.ab=h,d.j=k,d.O=a.style,d.zIndex=a.style.zIndex,d.Va=b,d.S=c,h=_.mb(d),c.Wa[h]=d,b.Wa[h]=d,b.j.na(d))};
var Jba=function(a){return _.La(a,function(a){var c={},d=a.path;if(50<=d.length){for(var e=[],f=d.length-2,g,h=2;h<f;h<<=1){for(var k=d[0],n=d[1],p=Math.ceil(f/(2*h)),q=Array(p),r=0,v=0,x=d.length-1-h;r<x;){var r=r+h,w=d[r],z=d[r+1],r=r+h;r>d.length-2&&(r=d.length-2);var F=d[r],D=d[r+1],E=w-k,H=z-n,k=F-k,P=D-n,U=E*k+H*P,n=k*k+P*P;U>=n?(w=F-w,z=D-z,z=w*w+z*z):0>=U?z=E*E+H*H:(z=E*P-H*k,z*=z,z/=n+1E-16);z=Math.sqrt(z);g&&(z+=Math.max(g[2*v],g[2*v+1]||0));q[v++]=z;k=F;n=D}v<p&&(q[v]=g?g[2*v]:0);g=q;e.push(q)}c.j=
e}c.O=a;a=f=window.Infinity;e=g=-window.Infinity;h=0;for(p=d.length;h<p;)q=d[h++],a=Math.min(a,q),e=Math.max(e,q),q=d[h++],f=Math.min(f,q),g=Math.max(g,q);d=new _.jf;d.ua=a;d.wa=e;d.ra=f;d.ya=g;c.Ta=d;return c})};var Kba=function(a,b,c,d){return _.La(a,function(a){var f=a.path;a=a.j;var g=null;if(b){for(var g=c?Lba(f):Mba(f,d),h={0:0},k=0,n=[0],p=1,q=a.length;p<q;++p){var r=a[p];r in h?k=h[r]:(k+=g(p-1),h[r]=k);n.push(k)}g=n}return{path:f,j:g}})};
var Mba=function(a,b){var c=_.ej(a);v1(c,b);return function(a){a*=2;var b=c[a]-c[a+2];a=c[a+1]-c[a+3];return Math.sqrt(b*b+a*a)}};var Lba=function(a){return function(b){b*=2;var c=new _.L(a[b],a[b+1]);b=new _.L(a[b+2],a[b+3]);return _.DA(c,b,1)}};var Nba=function(a){a.length&&(a=O2(a,Oba),a=O2(a,Pba));return a};
var O2=function(a,b){var c=[],d=new J1(0),e=new J1(0),f=new J1(0),g=Array(a.length);g[0]=a[0];g[1]=a[1];N1(a,d);for(var h=2,k=2;h<a.length;){c[0]=a[h];c[1]=a[h+1];N1(c,f);b(d,f,e)&&(O1(e,c),g[k++]=c[0],g[k++]=c[1]);g[k++]=a[h++];g[k++]=a[h++];var n=d,d=f,f=n}return g};var Oba=function(a,b,c){if(0<a.j==0<b.j)return!1;M1(a,b,P2);M1(P2,Q2,c);c.j=0;if(1E-12>L1(c,c))return!1;0>L1(c,a)+L1(c,b)&&(c.x=-c.x,c.y=-c.y);return!0};
var Pba=function(a,b,c){M1(a,b,P2);M1(Q2,P2,R2);M1(P2,R2,c);if(1E-12>L1(c,c)||0<L1(a,R2)==0<L1(b,R2))return!1;0>L1(c,a)+L1(c,b)&&(c.x=-c.x,c.y=-c.y,c.j=-c.j);return!0};var Qba=function(a,b,c){if(!b)return null;var d=[];b.forEach(function(a){d.push(Rba(a))});a&&_.G(d,_.MI);if(c)for(a=0,b=d.length;a<b;++a)d[a]=Nba(d[a]);return d};
var Sba=function(a){return _.La(a,function(a){var c;if(a.length){c=a[1];for(var d=[0],e=1,f=1;e<a.length/2;++e,++f){var g=a[2*e+1];if(180<Math.abs(c-g)){var h=g<c?1:-1,k=a[2*e-2],n=a[2*e];a.splice(2*e,0,n,g+360*h,n,g+450*h,90,g+450*h,90,c-450*h,k,c-450*h,k,c-360*h);d.push(f,f,f,f,f,f-1);e+=6}d.push(f);c=g}c=d}else c=[];return{path:a,j:c}})};var Rba=function(a){a=a.j;for(var b=a.length,c=Array(2*b),d=0,e=0;d<b;++d){var f=a[d];c[e++]=f.lat();c[e++]=f.lng()}return c};
var b2=function(a,b){var c={},d=a.get("icons"),e=!a.vb&&!!_.u(d),f=!0;c.j=[];e&&_.G(d,function(a){var b=_.nN(a.offset,["px","%"])||Tba;a=_.nN(a.repeat,["px","%"])||Uba;c.j.push({offset:b,repeat:a});f=f&&(0==b.value||"%"==b.tc)&&(0==a.value||"%"==a.tc)});var d=c.O=a.get("geodesic"),g=Qba(a.vb,a.get("latLngs"),d),g=Sba(g),h=d&&f;d&&e&&!h&&(g=Vba(g));g=Kba(g,e,h,b);e=c.P=Jba(g);if(1==e.length)d=e[0].Ta;else for(d=new _.jf,g=0,h=e.length;g<h;++g)_.uA(d,e[g].Ta);c.Ta=d;c.Vb=a;c.Wa={};return c};
var Vba=function(a){return _.La(a,function(a){return v2(a,_.Jh,.1)})};var Wba=function(a,b){this.P=_.lN;this.j=_.kN;this.O=a;this.S=b};
var a2=function(a,b){function c(a){return _.Na(b.get(a),f[a])}var d={},e=d.vb=b.vb,f=e?a.j:a.P;d.strokeColor=c("strokeColor");d.j=c("strokeOpacity");d.P=c("strokeWeight");d.Mb=c("clickable");e?(d.T=a.S?c("strokePosition"):a.j.strokePosition,d.fillColor=c("fillColor"),d.O=c("fillOpacity")):d.T=a.j.strokePosition;var g=b.get("zIndex")||0;d.zIndex=1E3*g+_.mb(b)%1E3;d.P=Math.min(d.P,0==d.T?32:16);d.V=b.get("hitStrokeWeight")||Xba(d.P,d.T);d.S=[];d.U=1;if(!e){var e=b.get("icons"),h=a.O,k=0;_.G(e,function(a){var b=
h(a.icon||{},d.strokeColor,d.j,d.P);b.T=!a.fixedRotation;d.S.push(b);k=Math.max(k,b.j);k=Math.max(k,b.O)});_.Ja(0,k)||(_.Ja(0,d.j)||_.Ja(0,d.P))&&1==d.S.length||(d.U=Math.max(k,d.j));_.u(e)&&(e=b.get("map"),_.Y(e,"Os"),_.il("Os","-p",b,!(!e||!e.Ga)))}return d};var Xba=function(a,b){switch(b){case 1:return 0;case 2:return 2*a;default:return a}};
var Yba=function(a){var b=a.__gm.V;if(!b.j){var c=a.__gm,d=_.hJ(),e=Zba(),f=new _.vc;(new Z1(b,f,new Wba(d,1==e))).bindTo("projection",a);var g=_.kf(-100,-200,100,200),d=new _.vc;new Iba(f,new _.VI(g),d,new _.VI(g),!(!a||!a.Ga));f=_.gk(a.getDiv());e=new K2(e,new _.O(256,256),_.rk,f);e=(0,_.t)(e.T,e);e=new C2(d,e);e.bindTo("projection",a);var h=new A2(d,c,function(b){return a.getProjection().fromPointToLatLng(b)});a.__gm.j.kc(h);_.RD(a,e,"overlayLayer",30);var k=new h2;k.bindTo("panes",c);k.bindTo("projection",
a);k.bindTo("zoom",c);k.bindTo("projectionCenterQ",c);k.bindTo("offset",c);_.I.bind(a,"click",k,k.td);_.M("geometry",function(d){var e=new S1(function(a,b,c){return a.get("geodesic")?new P1(a,b,c,d.computeHeading,d.computeOffset,d.computeOffsetOrigin):new R1(a,b,c)},a);X1(a,e);_.I.addListener(b,"insert",function(b){Y1(b,e);Dba(b,a,k,d.interpolate);oba(b,c,h,a.__gm.j);if(!b.P){var f=b.vb?"Op":"Ol";_.Y(a,f);_.il(f,"-p",b,!(!a||!a.Ga))}_.I.addListener(b,"click",function(){b.vb?b.P||_.il("Op","-i",b,
!(!a||!a.Ga)):_.il("Ol","-i",b,!(!a||!a.Ga))})})});_.I.addListener(b,"remove",function(a){_.G(a.oa,_.I.removeListener);delete a.draggable_changed;delete a.oa;_.jl("Od","-p",a);delete a.editable_changed;B2(a);_.I.trigger(k,"toolbar",{Lb:!1,Dc:a});a.U&&(_.I.removeListener(a.U),delete a.U);_.jl("Oe","-p",a);a.set("capturing",!1);delete a.capturing_changed;if(!a.P)if(a.vb)_.jl("Op","-p",a);else{_.jl("Ol","-p",a);var b=a.get("icons");_.u(b)&&_.jl("Os","-p",a)}})}};
var Zba=function(){var a=0;_.JB()?a=1:_.CD()&&(a=1==_.W.type&&_.Nj(_.W.version,8)?3:2);return a};var S2=function(a,b,c){if(!a||!b||!c)return null;var d=c.lat(),e=c.lng();c=b&1?d:a.O.O;var f=b&2?e:a.j.j,d=b&4?d:a.O.j,g=b&8?e:a.j.O;if(c>d){var h=c;c=d;d=h}b&10&&!a.j.contains(e)&&(h=_.dd(e,a.j.j),a=_.dd(a.j.O,e),b&2?h>a:a>h)&&(h=f,f=g,g=h);return _.hd(c,f,d,g)};
var T2=function(){var a=new _.Wf({clickable:!1,fillOpacity:0});a.bindTo("map",this);a.bindTo("strokeColor",this);a.bindTo("strokeOpacity",this);a.bindTo("strokeWeight",this);var b=new _.rv(["bounds","freeControlPoint","freeVertexPosition"],"return",S2);b.bindTo("bounds",this);b.bindTo("freeControlPoint",this);b.bindTo("freeVertexPosition",this);a.bindTo("bounds",b,"return");this.j=_.hN();this.j.bindTo("zIndex",this);a.bindTo("zIndex",this.j,"ghostZIndex")};
var U2=function(a,b){this.V=a;this.U=b;this.P=this.T=null;this.O=new _.Ib;_.I.bind(this.O,"set_at",this,this.jr);this.S=new _.Ib;_.I.bind(this.S,"set_at",this,this.kr);this.j=!1};
var V2=function(a,b,c){var d;d=c?new A1(a.O,$ba,aca,!1,b.overlayMouseTarget,a.U):new A1(a.S,bca,cca,!0,b.overlayMouseTarget,a.U);d.bindTo("projection",a);d.bindTo("zoom",a);d.bindTo("projectionCenterQ",a);d.bindTo("panningEnabled",a);d.bindTo("mapPixelBounds",a);d.bindTo("color",a);d.bindTo("zIndex",a);d.bindTo("offset",a);var e=a.V,f=c?W2:X2,g;_.I.addListener(d,"dragstart",function(b){g=a.get("bounds");e.bindTo("freeVertexPosition",d);e.set("freeControlPoint",f[b]);e.set("map",a.get("map"))});_.I.addListener(d,
"dragend",function(b,c){e.set("map",null);_.I.trigger(a,"toolbar",{Lb:!0,position:c,action:function(){a.set("bounds",g)}})});_.I.forward(d,"dragstart",a);_.I.forward(d,"dragend",a);_.I.forward(d,"panbynow",a);return d};var Y2=function(a){a&&(a.unbindAll(),a.release(),_.I.clearInstanceListeners(a))};var Z2=function(a,b,c){a.j||(a.j=!0,b=S2(a.get("bounds"),b,c),a.set("bounds",b),a.j=!1)};
var dca=function(a,b){function c(){a.get("editable")?eca(a,b):($2(a),_.I.trigger(a,"toolbar",{Lb:!1}))}a.editable_changed=c;c()};
var eca=function(a,b){if(!a.P){var c=new _.jN(a,!0);a.S=c;var d=new T2;d.bindTo("strokeColor",c);d.bindTo("strokeOpacity",c,"ghostStrokeOpacity");d.bindTo("strokeWeight",c);d.bindTo("bounds",a);d.bindTo("zIndex",a);a.T=d;var e=b.__gm;a.j=u1(e);var f=_.LI(e,a),g=_.Vj()?9:0,h=_.sk.T?new E1:new F1,d=new U2(d,function(b,c,d,e){return new x1(b,a.j||null,g,c,f,d,h,e)});d.set("map",b);d.bindTo("bounds",a);d.bindTo("panes",e);d.bindTo("projection",b);d.bindTo("zoom",e);d.bindTo("projectionCenterQ",e);d.bindTo("panningEnabled",
b,"draggable");d.bindTo("mapPixelBounds",e,"pixelBounds");d.bindTo("offset",e);d.bindTo("color",c,"strokeColor");d.bindTo("zIndex",a);d.bindTo("suppressGhostControlPoints",a);a.P=d;_.I.addListener(d,"dragstart",function(){a.set("capturing",!0)});_.I.addListener(d,"dragend",function(){a.set("capturing",!1)});_.I.forward(d,"panbynow",e);_.I.forward(d,"toolbar",a)}};
var $2=function(a){var b=a.P;b&&(b.unbindAll(),b.set("map",null),_.I.clearInstanceListeners(b),delete a.P,a.j.release(),delete a.j,a.set("capturing",!1),a.T.unbindAll(),delete a.T,a.S.release(),delete a.S)};var a3=function(a,b,c){this.O=a;this.Ua=c;a=a.get("bounds");this.S=a.getSouthWest();this.P=a.getNorthEast();this.j=c.fromDivPixelToLatLng(b)};
var b3=function(){var a=this,b=this.j=new _.Md;b.P=!0;b.bindTo("capturing",a);b.bindTo("cursor",a);b.bindTo("map",a);b.bindTo("strokeColor",a);b.bindTo("strokeOpacity",a);b.bindTo("strokeWeight",a);b.bindTo("strokePosition",a);b.bindTo("fillColor",a);b.bindTo("fillOpacity",a);b.bindTo("clickable",a);b.bindTo("zIndex",a);b.bindTo("suppressUndo",a);var c=this.O=[];_.G(z1,function(d){c.push(_.I.forward(b,d,a))});c.push(_.I.forward(a,"toolbar",b))};
var fca=function(a){var b=a.__gm.na;if(!b.j){var c=new S1(function(a,b,c){return new a3(a,b,c)},a);X1(a,c);b.j=function(b){Y1(b,c);var e=b.Xj=new b3;e.set("map",a);e.bindTo("bounds",b);e.bindTo("capturing",b);e.bindTo("cursor",b);e.bindTo("clickable",b);e.bindTo("fillColor",b);e.bindTo("fillOpacity",b);e.bindTo("strokeColor",b);e.bindTo("strokeOpacity",b);e.bindTo("strokeWeight",b);e.bindTo("strokePosition",b);e.bindTo("suppressUndo",b);e.bindTo("zIndex",b);var f=b.Na=[];_.G(z1,function(a){f.push(_.I.forward(e,
a,b))});f.push(_.I.forward(b,"toolbar",e));dca(b,a);_.Y(a,"Or");_.il("Or","-p",b,!(!a||!a.Ga));_.I.addListener(b,"click",function(){_.il("Or","-i",b,!(!a||!a.Ga))})};b.onRemove=function(a){var b=a.Xj;b.unbindAll();b.set("map",null);b.release();delete a.Xj;_.G(a.Na,_.I.removeListener);delete a.Na;delete a.editable_changed;$2(a);_.jl("Or","-p",a)}}};var c3=function(){};_.ef.prototype.Ge=_.li(6,function(a,b){this.j==a&&this.O==b&&(this.O=this.j=null)});
_.ef.prototype.He=_.li(5,function(a,b){this.j=a;this.O=b});var z1="click dblclick mousedown mousemove mouseout mouseover mouseup rightclick".split(" ");_.y(w1,_.J);w1.prototype.O=function(a,b,c,d,e){return!e&&d&&a?_.DA(d,a,c):b};_.y(x1,_.J);x1.prototype.release=function(){_.oj(this.j);_.G(this.Ba,_.I.removeListener);this.Ba.length=0;this.P.unbindAll();this.P.release();this.oa.unbindAll();this.U.set("active",!1)};x1.prototype.position_changed=function(){var a=this.get("position");if(a){var b=5+this.V;_.hk(this.j,new _.N(a.x-b,a.y-b))}};x1.prototype.color_changed=function(){var a=this.get("color");this.T.setBorderColor(this.j,a);y1(this)};_.y(A1,_.J);A1.prototype.release=function(){_.G(this.na,_.I.removeListener);this.na.length=0;_.G(this.j,(0,_.t)(this.oa,this));this.j.length=0;_.I.clearInstanceListeners(this.O);_.oj(this.O)};A1.prototype.zIndex_changed=function(){var a=this.get("zIndex")||0;this.S&&--a;_.qk(this.O,a)};
A1.prototype.T=function(a,b){function c(a){var b=e.index,c=f.get("pixelPosition");_.I.trigger(d,a,b,c)}var d=this,e={};e.index=b;d.j.splice(b,0,e);var f=new _.tD;f.bindTo("projection",d);f.bindTo("zoom",d);f.bindTo("center",d,"projectionCenterQ");f.bindTo("offset",d);f.set("latLngPosition",a);e.Od=f;var g=this.qa(d.O,d.V[b%d.V.length],d.U[b%d.U.length],d.S);g.bindTo("position",f,"pixelPosition");g.bindTo("color",d);g.bindTo("panningEnabled",d);g.bindTo("mapPixelBounds",d);e.j=g;var h=[_.I.addListener(g,
"dragstart",function(){d.bindTo("freeVertexPosition",f,"latLngPosition");c("dragstart")}),_.I.addListener(g,"dragend",function(){d.ta.setAt(e.index,f.get("latLngPosition"));c("dragend")}),_.I.forward(g,"panbynow",d)];_.G(z1,function(a){h.push(_.I.addListener(g,a,function(){c(a)}))});e.Na=h};A1.prototype.oa=function(a){a.j.unbindAll();a.j.release();a.Od.unbindAll();_.G(a.Na,_.I.removeListener);a.Na.length=0};_.y(C1,_.J);var gba=["pointer","row-resize","row-resize","col-resize","col-resize"],hba=[0,2,2,1,1];_.m=C1.prototype;_.m.map_changed=function(){this.get("map")||(this.P.set("map",null),D1(this),_.I.clearInstanceListeners(this.j))};_.m.panes_changed=function(){D1(this);this.O=fba(this)};
_.m.eq=function(){var a=this.j;a.clear();var b=this.get("center"),c=this.get("radius");if(b&&_.C(c)){var d=this.get("planetRadius"),e=_.Ka(c/d),f;f=_.A(b.lat());if(d=c/d){var c=Math.cos(d),d=Math.sin(d),g=Math.sin(f);f=Math.atan2(Math.sin(Math.acos((1-c)/d*Math.tan(f)))*d*Math.cos(f),c-g*g)}else f=0;f=_.Ka(f);a.push(b);c=b.lat()+e;90>c&&a.push(new _.L(c,b.lng()));e=b.lat()-e;-90<e&&a.push(new _.L(e,b.lng()));180>=f&&(e=b.lng()+f,f=b.lng()-f,a.push(new _.L(b.lat(),e)),a.push(new _.L(b.lat(),f)));this.Ae||
_.I.trigger(this,"toolbar",{Lb:!1})}};_.m.center_changed=C1.prototype.radius_changed=C1.prototype.planetRadius_changed=C1.prototype.eq;_.m.lr=function(a){var b=this.j.getAt(a);if(0==a)_.IA(this,function(){this.Ae=!0;this.set("center",b);this.Ae=!1},0);else{var c=_.DA(this.get("center"),b,this.get("planetRadius"));_.IA(this,function(){this.Ae=!0;this.set("radius",c);this.Ae=!1},0)}};E1.prototype.O=function(a,b,c,d,e){a=_.X("div",a,new _.N(b,b),new _.O(c,c));a.style.borderWidth=_.V(d);a.style.borderStyle="solid";a.style.borderRadius=_.V(Math.ceil(c/2+d));_.tk(a,e)};E1.prototype.setBorderColor=function(a,b){a.firstChild.style.borderColor=b};E1.prototype.j=function(a,b){a.firstChild.style.backgroundColor=b};F1.prototype.O=function(a,b,c,d,e){a.innerHTML="<gm_v:oval></gm_v:oval>";a=a.firstChild;_.hk(a,new _.N(b,b));_.nf(a,new _.O(c+1,c+1));_.ED(a).opacity=e;b=_.GD(a);b.opacity=e;b.weight=d};F1.prototype.setBorderColor=function(a,b){_.GD(a.firstChild).color=b};F1.prototype.j=function(a,b){_.ED(a.firstChild).color=b};var d3=new _.L(90,0),e3=new _.L(-90,0);H1.prototype.moveTo=function(a){a=this.Ua.fromDivPixelToLatLng(a);var b=this.P(a,this.j,this.S);b||(b=Math.abs(_.DA(a,d3)-this.j)<Math.abs(_.DA(a,e3)-this.j)?d3:e3);this.O.set("center",b)};_.y(I1,_.S);I1.prototype.center_changed=I1.prototype.radius_changed=I1.prototype.planetRadius_changed=function(){this.Ca()};I1.prototype.Ia=function(){var a=this.j;if(a){var b=this.get("radius"),c=this.get("center");_.C(b)&&c?(b/=this.get("planetRadius"),a.setPaths(kba(c,b))):a.setPaths([])}};I1.prototype.release=function(){for(var a=this.O,b=0,c=a.length;b<c;++b)_.I.removeListener(a[b]);this.O=null;this.j.unbindAll();this.j=null};P1.prototype.moveTo=function(a){var b=this;a=b.Ua.fromDivPixelToLatLng(a);var c=this.T(a,this.V,this.na);c?89<Math.abs(c.lat())&&(c=new _.L(_.Ha(c.lat(),-89,89),c.lng())):c=new _.L(this.O.lat(),a.lng()-this.P);b.j.get("latLngs").forEach(function(a,e){for(var f=0,g=a.getLength();f<g;++f){var h=b.U(c,b.S[e][f].ad,b.S[e][f].heading);a.setAt(f,h)}});this.O=c;this.P=a.lng()-c.lng()};_.y(Q1,_.Cj);R1.prototype.moveTo=function(a){var b=this.O.get("latLngs"),c=this.Ua,d=c.fromLatLngToDivPixel(this.j),e=new _.N(d.x-a.x,d.y-a.y);_.G(this.P,function(a,d){var h=b.getAt(d);_.G(a,function(a,b){var d=c.fromLatLngToDivPixel(a);d.x-=e.x;d.y-=e.y;h.setAt(b,c.fromDivPixelToLatLng(d))})})};_.y(S1,_.J);S1.prototype.release=function(){this.P&&(this.P.unbindAll(),this.P.release(),this.P=null);_.G(this.U,_.I.removeListener);this.U=null;_.G(this.Ba,_.I.removeListener);this.Ba=null;this.O&&_.nj(this.O);this.O=null};var T1=new _.O(30,30),U1=new _.N(T1.width/2,T1.height/2);_.m=S1.prototype;
_.m.active_changed=S1.prototype.panes_changed=S1.prototype.poly_changed=S1.prototype.projectionController_changed=function(){if(!this.get("active")&&!this.T){var a=this.get("panes"),b=this.get("projectionController"),c=this.get("poly");if(a!=this.S||b!=this.Ua||c!=this.j)this.S=a,this.Ua=b,this.j=c,_.G(this.Ba,_.I.removeListener),this.Ba=null,this.S&&this.Ua&&this.j?(this.Ba=_.Vj()?[_.I.bind(this.j,"mousedown",this,this.yp),_.I.bind(this.j,"mouseup",this,this.Ap)]:[_.I.bind(this.j,"mousemove",this,
this.zp)],this.bindTo("draggable",this.j)):(this.unbind("draggable"),this.set("draggable",!1))}};_.m.draggable_changed=function(){this.get("draggable")&&!_.Vj()?(this.S.overlayMouseTarget.appendChild(this.O),V1(this,!!this.get("active"))):this.O&&this.O.parentNode&&this.O.parentNode.removeChild(this.O)};_.m.Rl=function(a){_.cb(a);W1(this,"click",a)};_.m.Vl=function(a){this.set("mousedown",!0);V1(this,!0);W1(this,"mousedown",a)};
_.m.Xl=function(a){V1(this,!1);this.set("mousedown",!1);W1(this,"mouseup",a)};_.m.Wl=function(a){this.get("active")?_.cb(a):W1(this,"mousemove",a)};_.m.zp=function(a){if(a=a.Fb)a=_.gl(a,this.S.overlayMouseTarget),this.set("position",a)};_.m.ii=function(){var a=this.get("position");this.set("dragging",!0);this.oa=this.V(this.j,a,this.Ua);this.j.set("capturing",!0);W1(this,"dragstart");this.na=this.j.get("editable");this.j.set("editable",!1)};
_.m.fg=function(){this.j.set("editable",this.na);W1(this,"dragend");this.j.set("capturing",!1);this.set("dragging",!1)};_.m.position_changed=function(){var a=this.get("position");_.Vj()||_.hk(this.O,new _.N(a.x-U1.x,a.y-U1.y));this.get("dragging")&&(this.oa.moveTo(a),W1(this,"drag"))};_.m.Tl=function(a){a&&_.tl(a)||!this.T||!this.j||this.get("dragging")||(a=this.Ua.fromLatLngToDivPixel(a.latLng),this.set("position",a),this.ii())};
_.m.Ul=function(a){if(this.get("dragging")){if(1!=a.scale)this.fg();else if(this.T){var b=this.Ua.fromLatLngToDivPixel(a.latLng);this.set("position",b)}_.qC(a)}};_.m.Sl=function(a){this.get("dragging")&&(this.fg(),_.qC(a))};_.m.yp=function(){this.T=!!this.get("draggable")};_.m.Ap=function(){this.T=!1};_.y(Z1,_.J);Z1.prototype.projection_changed=function(){var a=this;a.V.forEach(function(b){if(b.get("icons")){var c=_.mb(b);a.j[c]=b;d2(b)}});e2(a)};var pba={latLngs:1,geodesic:1,icons:1},qba={strokeColor:1,strokeOpacity:1,strokePosition:1,strokeWeight:1,fillColor:1,fillOpacity:1,hitStrokeWeight:1,zIndex:1,clickable:1,icons:1};_.y(h2,_.J);_.m=h2.prototype;_.m.panes_changed=function(){var a=this.O,b=this.get("panes");b?b.floatPane.appendChild(a):a.parentNode&&_.oj(a)};_.m.td=function(){_.AC(this.O);this.S=null;k2(this);this.P=null};_.m.changed=h2.prototype.td;_.m.Yl=function(a){a.Lb?a.Dc.get("suppressUndo")?this.td():uba(this,a.position,a.action,a.Dc):a.Dc==this.P&&this.td()};_.m.Rp=function(a){_.Za(a);this.S();this.td()};_.m.Hf=function(a){_.$B(this.j,j2,a)};
var rba=_.Ck("undo_poly"),j2=new _.O(30,27),i2=_.tg,sba=new _.N(30,0),tba=new _.N(60,0),l2=new _.N(10,-11);m2.prototype.getLength=function(){var a=this.j.getLength();1<a&&++a;return a};m2.prototype.getAt=function(a){this.j.getLength()==a&&1<a&&(a=0);return this.j.getAt(a)};_.y(n2,_.J);_.m=n2.prototype;_.m.release=function(){_.G(this.Ba,_.I.removeListener)};_.m.Zp=function(){var a=this.get("projection"),b=this.P;if(a)for(var c=this.O,d=c.getLength(),e=this.get("geodesic"),f=0;f<d-1;++f)b.setAt(f,p2(c.getAt(f),c.getAt(f+1),e,a,this.j));else b.clear()};_.m.geodesic_changed=n2.prototype.projection_changed=n2.prototype.Zp;_.m.$k=function(a){o2(this,!1,a)};_.m.Yh=function(a){o2(this,!0,a)};
_.m.Zk=function(a){var b=this.get("projection");if(b){var c=this.O,d=this.P,e=this.get("geodesic");a<c.getLength()?(0<a&&d.setAt(a-1,p2(c.getAt(a-1),c.getAt(a),e,b,this.j)),d.removeAt(a)):0<a&&d.removeAt(a-1)}};_.y(q2,_.J);q2.prototype.map_changed=function(){this.get("map")||(this.T.set("map",null),u2(this))};
q2.prototype.panes_changed=q2.prototype.paths_changed=q2.prototype.suppressGhostControlPoints_changed=function(){var a=this;u2(a);var b=a.get("paths"),c=a.get("panes");if(b&&c){var d=c.overlayMouseTarget;b.forEach(function(b){a.O.push(r2(a,b,d));a.get("suppressGhostControlPoints")||a.j.push(t2(a,b,d))});var e=function(){_.I.trigger(a,"toolbar",{Lb:!1})};e();c=a.U;c.push(_.I.addListener(b,"insert_at",function(c){var g=a.get("suppressGhostControlPoints"),h=b.getAt(c);a.O.splice(c,0,r2(a,h,d));g||a.j.splice(c,
0,t2(a,h,d));e()}));c.push(_.I.addListener(b,"remove_at",function(b){var c=a.get("suppressGhostControlPoints");a.P(a.O[b]);a.O.splice(b,1);c||(a.P(a.j[b]),a.j.splice(b,1));e()}));c.push(_.I.addListener(b,"set_at",function(c){var g=a.get("suppressGhostControlPoints");a.P(a.O[c]);var h=b.getAt(c);a.O[c]=r2(a,h,d);g||(a.P(a.j[c]),a.j[c]=t2(a,h,d));e()}))}};q2.prototype.P=function(a){a.unbindAll();a.release();_.I.clearInstanceListeners(a);a.P&&(a.P.release(),a.P.unbindAll())};z2.prototype.getBounds=_.l("O");A2.prototype.j=function(a,b){var c=a.Ja,d=null,e=new _.N(0,0),f=new _.N(0,0),g;this.P.forEach(function(a){if(!d){g=1<<a.zoom;f.x=256*a.La.x;f.y=256*a.La.y;var b=e.x=Math.round(c.x*g-f.x)+.5,h=e.y=Math.round(c.y*g-f.y)+.5;0<=b&&256>b&&0<=h&&256>h&&(d=a)}});if(!d)return null;var h=[],k=d.Wa,n;for(n in k)h.push(k[n]);h.reverse();h.sort(function(a,b){return b.zIndex-a.zIndex||0});k=null;n=b?15:0;for(var p=0,q=h.length;p<q;++p){var r=h[p],v=r.O;if(v.Mb){var x=r.S.Vb,w=v.V/2+n,r=Cba(r.ab);if(w=bba(e.x,
e.y,w,r)){k=x;h=a.Ja=new _.N((w[0]+f.x)/g,(w[1]+f.y)/g);a.latLng=this.S(h);break}if(v.vb&&!b&&cba(e.x,e.y,r)){k=x;break}}}return k};A2.prototype.handleEvent=function(a,b,c){if("mouseout"==a)this.O.set("cursor","");else if("mousemove"==a){var d=c.get&&c.get("cursor");_.B(d)||(d="pointer");this.O.set("cursor",d)}_.I.trigger(c,a,new Q1(b.latLng,b.Fb))};A2.prototype.zIndex=30;_.y(C2,_.J);C2.prototype.projection=null;C2.prototype.maxZoom=30;C2.prototype.getTile=function(a,b,c){c=c.createElement("div");_.nf(c,this.tileSize);c.style.overflow="hidden";var d=this.get("projection"),d=new z2(a,b,d),e=d.getBounds(),f=this.O(c),g={};g.Ta=e;g.La=a;g.Ha=c;g.j=f;g.Wa={};g.O=d;g.zoom=b;c.Va=g;_.wc(this.j,g);return c};C2.prototype.releaseTile=function(a){var b=a.Va;a.Va=null;this.j.remove(b);_.jk(a,"")};D2.prototype.na=function(a){this.O[_.mb(a)]=a;G2(this)};D2.prototype.ta=function(a){delete this.O[_.mb(a)];G2(this)};D2.prototype.S=function(){G2(this)};I2.prototype.na=function(a){var b=a.element=J2(this);_.hk(b,_.tg);for(var c=a.ab,d=[],e=0,f=c.length;e<f;++e)for(var g=c[e],h=0,k=g.length;h<k;h+=2)d.push(h?"l":"m"),d.push(Math.round(g[h]),Math.round(g[h+1]));d.push("e");b.path=d.join(" ");a.P=[];b=0;for(c=a.j.length;b<c;++b)a.P.push(Hba(this,a.j[b]));this.S(a)};I2.prototype.ta=function(a){_.oj(a.element);delete a.element;_.G(a.P,function(a){_.G(a,_.oj)});delete a.P};
I2.prototype.S=function(a){var b=a.O,c=a.element;_.qk(c,b.zIndex);_.FD(c,b.fillColor,b.O);_.HD(c,b.strokeColor,b.j,b.P);for(var c=0,d=b.S.length;c<d;++c)for(var e=a.P[c],f=b.S[c],g=b.zIndex,h=a.j[c],k=this.P.Zb(f.S,f.scale),n=0,p=void 0;p=e[n];++n)p.path=k,_.qk(p,g),_.FD(p,f.fillColor,f.O),_.HD(p,f.strokeColor,f.j,f.P),p.style.rotation=Math.round(_.Ka(f.rotation+(f.T?h[3*n+2]:0)))};K2.prototype.T=function(a,b){switch(this.U){case 1:return this.j||(this.j=Gba(this.O,a)),new D2(b,this.P,this.j,a);case 2:return new I2(b,this.P,!1,this.S,new _.SI);case 3:return new I2(b,this.P,!0,this.S,new _.SI);default:return null}};var Q2=new J1(1),P2=new J1(0),R2=new J1(0);var Tba={value:100,tc:"%"},Uba={value:0,tc:"px"};_.y(T2,_.J);_.y(U2,_.J);var W2=[12,6,9,3],X2=[1,2,4,8],$ba=["ne-resize","nw-resize","se-resize","sw-resize"],bca=["row-resize","col-resize"],aca=[0],cca=[2,1];_.m=U2.prototype;_.m.map_changed=function(){this.get("map")||(this.V.set("map",null),Y2(this.T),this.get("suppressGhostControlPoints")||Y2(this.P),_.I.clearInstanceListeners(this.O))};
_.m.panes_changed=U2.prototype.suppressGhostControlPoints_changed=function(){Y2(this.T);Y2(this.P);this.P=null;var a=this.get("panes");a&&(this.T=V2(this,a,!0),this.get("suppressGhostControlPoints")||(this.P=V2(this,a,!1)))};
_.m.bounds_changed=function(){var a=this.O,b=this.S,c=this.get("bounds");if(c){this.j=!0;a.setAt(0,c.getNorthEast());a.setAt(1,new _.L(c.O.j,c.j.j,!0));a.setAt(2,_.BA(c));a.setAt(3,c.getSouthWest());var a=c.O.Mc(),d=c.j.Mc();b.setAt(0,new _.L(c.O.O,d));b.setAt(1,new _.L(a,c.j.j));b.setAt(2,new _.L(c.O.j,d));b.setAt(3,new _.L(a,c.j.O));this.j=!1;_.I.trigger(this,"toolbar",{Lb:!1})}else a.clear(),b.clear()};_.m.jr=function(a){Z2(this,W2[a],this.O.getAt(a))};_.m.kr=function(a){Z2(this,X2[a],this.S.getAt(a))};a3.prototype.moveTo=function(a){var b=this.Ua,c=b.fromLatLngToDivPixel(this.j),d=b.fromLatLngToDivPixel(this.S),b=b.fromLatLngToDivPixel(this.P),b=new _.N(b.x-c.x+a.x,b.y-c.y+a.y);a=new _.gd(this.Ua.fromDivPixelToLatLng(new _.N(d.x-c.x+a.x,d.y-c.y+a.y)),this.Ua.fromDivPixelToLatLng(b));this.O.set("bounds",a)};_.y(b3,_.J);b3.prototype.bounds_changed=function(){var a=this.j;if(a){var b=this.get("bounds");if(b){var c=b.getSouthWest(),d=b.getNorthEast(),b=b.getCenter();a.setPaths([new _.L(d.lat(),d.lng()),new _.L(d.lat(),b.lng()),new _.L(d.lat(),c.lng()),new _.L(c.lat(),c.lng()),new _.L(c.lat(),b.lng()),new _.L(c.lat(),d.lng())])}else a.setPaths([])}};b3.prototype.release=function(){for(var a=this.O,b=0,c=a.length;b<c;++b)_.I.removeListener(a[b]);delete this.O;this.j.unbindAll();delete this.j};c3.prototype.Gm=function(a){var b=0!=a.getVisible()?a.getMap():null;a.O!=b&&(a.O&&a.O.__gm.P.remove(a),b&&(nba(b),_.wc(b.__gm.P,a)),a.O=b)};c3.prototype.Nm=function(a){var b=0!=a.getVisible()?a.getMap():null;a.S!=b&&(a.S&&a.S.__gm.V.remove(a),b&&(Yba(b),_.wc(b.__gm.V,a)),a.S=b)};c3.prototype.Om=function(a){var b=0!=a.getVisible()?a.getMap():null;a.O!=b&&(a.O&&a.O.__gm.na.remove(a),b&&(fca(b),_.wc(b.__gm.na,a)),a.O=b)};_.oc("poly",new c3);});
