google.maps.__gjsload__('usage', function(_){'use strict';var A7=function(a){this.N=a||[]};var B7=function(a){this.N=a||[]};var C7=function(a){this.N=a||[]};var D7=function(){if(!E7){var a=[];E7={ka:-1,ma:a};a[1]={type:"s",label:1,R:""};a[2]={type:"s",label:1,R:""};a[3]={type:"e",label:1,R:0};a[4]={type:"v",label:1,R:0};a[5]={type:"v",label:1,R:0};if(!F7){var b=[];F7={ka:-1,ma:b};b[1]={type:"s",label:1,R:""};b[2]={type:"v",label:1,R:0}}a[6]={type:"m",label:3,$:F7}}return E7};
var G7=function(a){if(!H7){var b=[];H7={ka:-1,ma:b};b[1]={type:"m",label:3,$:D7()}}return _.Ag.j(a.N,H7)};var I7=function(a){this.j=[];this.O=a};var J7=function(a,b){this.O=null;this.j=b;_.QC(this,"center mapTypeId heading tilt zoom bounds".split(" "),a);this.O=K7(this);var c=this.j;L7(c,"mapview");c.P&&M7(c,c.O,"channel",c.P)};var K7=function(a){return{Ta:a.get("bounds"),Mc:a.get("center"),nb:a.get("mapTypeId"),heading:a.get("heading")||0,Cb:a.get("tilt")||0,zoom:a.get("zoom"),wj:!1}};
var Mda=function(a){a.P&&window.clearTimeout(a.P);a.P=window.setTimeout(function(){a.P=null;var b=a.O,c=a.O=K7(a),d=!1;b.nb!=c.nb&&(d=a.j,L7(d,"maptype",c.nb),L7(d,"interaction","maptype"),d=!0);b.wj&&(L7(a.j,"interaction","jump"),d=!0);b.zoom<c.zoom?(d=a.j,L7(d,"zoom",c.zoom),L7(d,"zoomInteraction","in"),L7(d,"interaction","zoom"),d=!0):b.zoom>c.zoom&&(d=a.j,L7(d,"zoom",c.zoom),L7(d,"zoomInteraction","out"),L7(d,"interaction","zoom"),d=!0);b.heading!=c.heading&&(d=a.j,L7(d,"heading",c.heading),L7(d,
"interaction","heading"),d=!0);b.Cb!=c.Cb&&(d=a.j,L7(d,"tilt",c.Cb),L7(d,"interaction","tilt"),d=!0);d||b.Mc==c.Mc||L7(a.j,"interaction","pan")},100)};var N7=function(a,b,c){this.T=a;this.O="ut|client:"+b;this.S=(this.P=c)&&this.O+"|channel:"+c;this.j=new _.xc(0,0,0)};var L7=function(a,b,c,d){M7(a,a.O,b,c,d);a.S&&M7(a,a.S,b,c,d)};
var M7=function(a,b,c,d,e){var f=new A7;f.N[0]=b;f.N[1]=c;null!=d?(b=[],_.Q(f.N,5).push(b),b=new B7(b),b.N[0]=""+d,b.N[1]=e||1):f.N[4]=e||1;a=a.T;a.j.length||(0,window.setTimeout)((0,_.t)(a.P,a),5E3);a.j.push(f)};var Nda=function(a){if(!a)return null;a=a.routes;if(!_.u(a))return null;a=a[0].legs;for(var b=0,c=0;c<a.length;++c){var d=a[c].distance;if(d)b+=d.value;else return null}return b};var Oda=function(){return _.dj()%1679616};
var O7=function(a){_.Lk(window.document,Oda,_.ux+"/maps/api/js/StatsService.RecordStats",_.Rf,a,_.ra)};var P7=function(){this.O=new N7(new I7(O7),_.Se(_.R),_.qi())};var E7,F7,H7;A7.prototype.W=_.l("N");A7.prototype.jd=function(){var a=this.N[4];return null!=a?a:0};B7.prototype.W=_.l("N");B7.prototype.jd=function(){var a=this.N[1];return null!=a?a:0};C7.prototype.W=_.l("N");I7.prototype.P=function(){for(var a=0,b=null,c=0,d;d=this.j[c];++c){var e=d,f=D7(),e=_.Ag.j(e.N,f).length;b&&1750<a+e&&(this.O(G7(b)),b=null,a=0);b||(b=new C7);f=[];_.Q(b.N,0).push(f);_.hi((new A7(f)).N,d?d.N:null);a+=e}this.O(G7(b));this.j.length=0};_.y(J7,_.J);J7.prototype.changed=function(a){null!=this.O&&("bounds"==a&&(this.get("bounds").intersects(this.O.Ta)||(this.O.wj=!0),this.O.Ta=this.get("bounds")),Mda(this))};var Q7=[10,20,30,40,50,60,70,80,90,100,window.Infinity],R7=[1,2,5,10,20,50,100,200,500,window.Infinity];_.m=N7.prototype;_.m.Zq=function(a,b){if(b==_.ga){var c;if(a)a:{if(c=a[0].address_components)for(var d=0;d<c.length;d++)if(_.Hj(c[d].types,"country")){c=c[d].short_name;break a}c=null}else c=null;L7(this,"geocodeCountry",c||"ZZ")}L7(this,"geocodeStatus",b)};
_.m.Wq=function(a,b){L7(this,"directionsStatus",b);var c=Nda(a);if(c){for(var d,e=0;e<R7.length;++e)if(1E3*R7[e]>c){d=R7[e];break}L7(this,"directionsDistanceTotal",d,c);L7(this,"directionsDistance",d)}};_.m.Xq=function(a,b){L7(this,"distanceMatrixStatus",b);if(b==_.ga){for(var c=a.origins.length*a.destinations.length,d,e=0;e<Q7.length;++e)if(Q7[e]>c){d=Q7[e];break}L7(this,"distanceMatrixElementsTotal",d,c);L7(this,"distanceMatrixElements",d)}};_.m.Yq=function(a){L7(this,"elevationStatus",a)};
_.m.cr=function(a){L7(this,"placeSearchStatus",a)};_.m.br=function(a){L7(this,"placeQueryStatus",a)};_.m.ar=function(a){L7(this,"placeDetailsStatus",a)};_.m.$q=function(a){a&&L7(this,"placeAutocomplete")};_.m.fr=function(a){_.Ea(this.j,a);L7(this,"streetviewStart")};_.m.dr=function(){L7(this,"streetviewMove")};
_.m.er=function(a){this.j.heading!=a.heading&&L7(this,"streetviewPov","heading");this.j.pitch!=a.pitch&&L7(this,"streetviewPov","pitch");this.j.zoom!=a.zoom&&L7(this,"streetviewPov","zoom");_.Ea(this.j,a)};P7.prototype.j=function(a){new J7(a,new N7(new I7(O7),_.Se(_.R),_.qi()))};_.oc("usage",new P7);});
